FROM jarredsumner/bun:edge

WORKDIR /gehenna

COPY tsconfig.json ./tsconfig.json
COPY package.json ./package.json
COPY bun.lockb ./bun.lockb
COPY src ./src

RUN bun install

CMD ["bun", "run", "start"]
